//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkParserAnother.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LinkParserAnother.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;email@example.com&quot;
        ///first&apos;name.lastname@example.com
        ///email@subdomain-example.com
        ///firstname+lastname@example.com
        ///test@2s-company.com
        ///email@123.123.123.123
        ///1234567890@example.com
        ///email@example-one.com
        ///_______@example.com
        ///email@example.name
        ///email@example.museum @mail.ru
        ///email@example.co.jp
        ///firstname-lastname@example.com
        ///hhhhhhhhhhhhh www.google.com.ua hhhhhhhhhhhh
        ///https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore#msbuild-integrated-restore
        ///https://www.intertech.com/Blog/c-sh [rest of string was truncated]&quot;;.
        /// </summary>
        public static string rawSample {
            get {
                return ResourceManager.GetString("rawSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email@example.com
        ///first&apos;name.lastname@example.com
        ///email@subdomain-example.com
        ///firstname+lastname@example.com
        ///test@2s-company.com
        ///email@123.123.123.123
        ///1234567890@example.com
        ///email@example-one.com
        ///_______@example.com
        ///email@example.name
        ///email@example.museum
        ///email@example.co.jp
        ///firstname-lastname@example.com
        ///www.google.com.ua
        ///https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore#msbuild-integrated-restore
        ///https://www.intertech.com/Blog/c-sharp-tutorial-understanding-c-events/
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sample {
            get {
                return ResourceManager.GetString("sample", resourceCulture);
            }
        }
    }
}
